DROP SCHEMA IF EXISTS `Millionaires`;
CREATE SCHEMA `Millionaires` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `Millionaires`;
DROP TABLE IF EXISTS `Questions`;
CREATE TABLE `Questions` (
	`id` int(3) NOT NULL AUTO_INCREMENT,
	`question` varchar(200) NOT NULL ,
	`answerA` varchar(100) NOT NULL ,
	`answerB` varchar(100) NOT NULL ,
	`answerC` varchar(100) NOT NULL ,
	`answerD` varchar(100) NOT NULL ,
	`correctAnswer` varchar(1) NOT NULL ,
	`points` int(7) NOT NULL ,
	PRIMARY KEY (`id`)
);
ALTER DATABASE Millionaires CHARACTER SET utf8 COLLATE utf8_polish_ci;

INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Zwarta grupa zawodników jadących w wyścigu kolarskim to:','aktyw','peleton','konwój','plejada','b','10'),
('Który z wymienionych pojazdów nie jest wyposażony w gąsienice ?','czołg','ratrak','autokar','koparka','c','10'),
('Mężczyzna zabiegający o względy kobiety to:','administrator','orator','kombinator','adorator','d','10'),
('W aeroklubie nie jest zrzeszony:','spadochroniarz','autopilot','modelarz lotniczy','pilot sportowy','b','10'),
('Który z wymienionych ptaków nie potrafi latać ?','orzeł','tukan','struś','albatros','c','10'),
('Jaka figura geometryczna jest również instrumentem muzycznym ?','koło','trapez','trójkąt','romb','c','10'),
('Co Kopciuszek zgubił na schodach pałacu ?','chusteczkę','pantofelek','parasolkę','torebkę','b','10'),
('Co sadzimy na rabatkach ?','kwiaty','żyto','buraki cukrowe','drzewa','a','10'),
('W Wenecji popularnym środkiem lokomocji jest:','katamaran','gondola','tratwa','piroga','b','10'),
('Ludzi, którzy w czasie zimy zażywają kąpieli, na przykład w morzu, nazywamy:','morsami','fokami','bieługami','rekinami','a','10'),
('Parząca roślina to:','perz','mniszek','pokrzywa','skrzyp','c','10'),
('Konstrukcja ułatwiająca wyciąganie wiader z wodą ze studni to:','czapla','bocian','kormoran','żuraw','d','10'),
('Osoba przekazująca obcemu państwu wiadomości będące tajemnicą państwową to:','szmugler','szpieg','szuler','hochsztapler','b','10'),
('Kwiat rabatowy otwierający się i intensywnie pachnący dopiero po zmroku to:','bratek','niezapominajka','maciejka','nasturcja','c','10'),
('Zabawa dziecięca z zaklepywaniem to:','chowany','klasy','pomidor','klipa','a','10'),
('Czym w hokeju odbijamy krążek ?','kijem','pałką','młotkiem','rakietą','a','10'),
('Które z wymienionych zwierząt nie ma kolców ?','jeż','kolczatka','nosorożec','jeżozwierz','c','10'),
('Jak nazywa się zasłona w teatrze oddzielająca scenę od widowni ?','portiera','kurtyna','parawan','lambrekin','b','10'),
('Czerwiec zaczyna się Dniem:','Babci','Dziadka','Matki','Dziecka','d','10'),
('Jaką bronią posługuje się Eros ?','kuszą','procą','dwururką','łukiem','d','10'),
('Co zgodnie z tradycją robimy w Śmigus-Dyngus ?','stroimy choinkę','malujemy jajka','oblewamy się wodą','mówimy nieprawdę','c','10'),
('Ząb pokryty jest:','szkliwem','zgorzeliną','politurą','powłoką','a','10'),
('Do jakiego miasta usilnie próbował dojść Koziołek Matołek ?','do Piotrkowa','do Sulejowa','do Tomaszowa','do Pacanowa','d','10'),
('Jak stwór prześladował królestwo króla Kraka ?','smok','cyklop','wąż morski','gryf','a','10'),
('Co ukazuje się w słoneczny dzień po deszczu ?','zorza','tęcza','dym','mgła','b','10'),
('Legendarny człowiek lasu, wychowany przez małpy w afrykańskiej dżungli to:','Conan','Bambo','Tarzan','Robinson Crusoe','c','10'),
('Ptak w gospodarstwie domowym, który jest budzikiem gospodarza i udręką śpiocha to:','indyk','kaczka','kogut','perlica','c','10'),
('Serial telewizyjny z udziałem publiczności albo nagranym śmiechem to:','sitcom','remake','remixing','sequel','a','10'),
('Ile osób liczy drużyna piłkarska znajdująca się na boisku ?','6','8','10','11','d','10'),
('Jak nazywa się zimowa przerwa w nauce ?','teleferie','ferie','wakacje','majówka','b','10'),
('Płytkie miejsce pozwalające przejść przez rzekę na drugą stronę to:','bród','przecinka','dróżka','wąwóz','a','10'),
('Atrybutem wróżki nie jest:','czarny kot','kryształowa kula','talia kart','bilardowa kula','d','10'),
('Alkohol z bąbelkami to:','whisky','gin','szampan','rum','c','10'),
('Dokąd, według przysłowia, ciągnie wilka ?','do kurnika','do ZOO','w góry','do lasu','d','10'),
('Tradycyjny dom ludów żyjących w strefie polarnej, wykonany z bloków śniegu lub lodu to:','igloo','wigwam','szałas','jurta','a','10'),
('Do wykonania omleta niezbędne są:','pomidory','twaróg','jajka','buraki','c','10'),
('Pyszny owoc rośliny z rodziny dyniowatych lub synonim odrzuconych oświadczyn to:','kabaczek','patison','ogórek','arbuz','d','10'),
('Jak według Biblii miał na imię pierwszy mężczyzna ?','Kain','Abel','Adam','Noe','c','10'),
('Które z poniższych zwierząt ma „torbę” ?','krokodyl','struś','bóbr','kangur','d','10'),
('Zabawka dziewczynek i przyrząd treningowy bokserów to:','skakanka','piłka plażowa','lalka Barbie','ringo','a','10'),
('Przedstawicielem jakiego plemienia był Winnetou ?','Siuksów','Wron','Czejenów','Apaczów','d','10'),
('Kraj o największej liczbie mieszkańców to:','Francja','Hiszpania','Rosja','Chiny','d','10'),
('Naczynie przeznaczone do hodowania kwiatów to:','makutra','doniczka','moździerz','cebrzyk','b','10'),
('Drugą literą w alfabecie greckim jest:','beta','alfa','gamma','sigma','a','10'),
('Szyk, w jakim lecą żurawie, nazywamy:','kluczem','eskadrą','konwojem','kolumną','a','10'),
('Tradycyjne urodzinowe ciasto to:','sękacz','kołacz','tort','mazurek','c','10'),
('Co chroni głowę motocyklisty ?','beret','kominiarka','kapelusz','kask','d','10'),
('Akrobata sportowy dublujący aktora w scenach zbyt ryzykownych to:','kirasjer','kaskader','butafor','szwenkier','b','10'),
('Słynną chińską zupę sporządza się z gniazd:','bocianich','kukułczych','jaskółczych','łabędzich','c','10'),
('Szklany pojemnik, w którym hoduje się ryby to:','terrarium','serpentarium','woliera','akwarium','d','10'),
('Jak nazywa się wycieczka kajakarzy wytyczonym szlakiem wodnym ?','spływ','spław','zjazd','zlot','a','10'),
('Ile prostych można przeprowadzić przez dwa różne punkty ?','jedną','dwie','trzy','cztery','a','10'),
('W jakim włoskim mieście znajduje się słynna Krzywa Wieża ?','w Pizie','w Bolonii','w Weronie','w Padwie','a','10'),
('Wielka Pardubicka to wyścigi:','psich zaprzęgów','konne','saneczkarskie','kolarskie','b','10'),
('Jakim kolorem na mapie fizycznej oznacza się wyżyny ?','niebieskim','zielonym','żółtym','brązowym','c','10'),
('Jak nazywa się świątynia wyznawców prawosławia ?','cerkiew','meczet','pagoda','minaret','a','10'),
('Który z wymienionych kotów żyje w Polsce w warunkach naturalnych ?','serwal','żbik','karakal','ocelot','b','10'),
('Hollywood to centrum amerykańskiego przemysłu:','hutniczego','węglowego','filmowego','rolniczego','c','10'),
('Czyją śmierć opłakiwał Jan Kochanowski w swoich trenach ?','córki','przyjaciółki','siostry','matki','a','10'),
('Kogel-mogel otrzymujemy, ucierając żółtka:','z mąką','z makiem','z cukrem','z solą','c','10'),
('Która spośród wymienionych liczb jest nieparzysta ?','12','56','65','76','c','10'),
('O której godzinie cień jest najkrótszy ?','o ósmej','w południe','o piętnastej','o osiemnastej','b','10'),
('Solowa pieśń operowa z akompaniamentem orkiestry to:','aria','oratorium','preludium','fuga','a','10'),
('Człowiek nadmiernie gromadzący zapasy nazywany jest:','susłem','wielbłądem','chomikiem','turem','c','10'),
('Ile miesięcy trwa prawidłowo przebiegająca ciąża u człowieka ?','sześć','dziewięć','jedenaście','dwanaście','c','10'),
('W jakim sklepie kupujemy igły, nici i guziki ?','w trafice','w jatce','w pasmanterii','w drogerii','c','10'),
('Życie jakich zwierząt bada ornitolog ?','ptaków','owadów','waleni','ryb','a','10'),
('Cztery minuty to:','120 sekund','180 sekund','240 sekund','300 sekund','c','10'),
('Ile głosek jest w wyrazie „chaszcze” ?','cztery','pięć','sześć','osiem','b','10'),
('W jakiej dyscyplinie sportu używa się szabli, floretów i szpad ?','w biathlonie','w szermierce','w chodzie','w kręglarstwie','b','10'),
('Ile piątek mieści się w liczbie 60 ?','siedem','dziewięć','jedenaście','dwanaście','d','10'),
('Z jakiej części krzewu herbacianego otrzymujemy herbatę ?','z liści','z gałązek','z korzeni','z kwiatów','a','10'),
('Oranż to kolor:','purpurowy','karminowy','pomarańczowy','karmazynowy','c','10'),
('Które z wymienionych miast nie leży nad Wisłą ?','Grudziądz','Kalisz','Warszawa','Tarnobrzeg','b','10'),
('Jaką część rośliny jesz, chrupiąc marchewkę ?','nać','łodygę','kwiat','korzeń','d','10'),
('Jakiego człowieka nazywamy żartobliwie „lelum-polelum” ?','jąkającego się','flegmatycznego','nadpobudliwego','ciężko pracującego','b','10'),
('Do kogo chodził w odwiedziny Czerwony Kapturek ?','do dziadka','do cioci','do babci','do wujka','c','10'),
('Co buduje się w stoczni ?','statki wodne','samoloty','tramwaje','pociągi','a','10'),
('Udawać, że nic się nie wie, to „chować głowę...” :','w siano','w worek','w cień','w piasek','d','10'),
('Wieniec na głowie starożytnych Greków, symbolizujący zwycięstwo to:','laurencja','laurka','laur','laufer','c','10'),
('Jaki kraj nazywamy „krainą kwitnącej wiśni” ?','Japonię','Holandię','Czechy','Rosję','a','10'),
('Ostatnia ławka w klasie szkolnej, w której sadzano najgorszych uczniów to:','zajęcza ławka','ośla ławka','barania ławka','kozia ławka','b','10'),
('Na co trafiła przysłowiowa kosa ?','na płot','na sęk','na kamień','na kosę','c','10'),
('Co jest owocem grochu ?','strąk','kolba','orzech','jagoda','a','10'),
('Bezdomny włóczęga to:','marszand','kuglarz','kloszard','korsarz','c','10'),
('Niewykonalne zadanie to „kwadratura...” :','koła','trójkąta','rombu','trapezu','a','10'),
('Jak nazywamy człowieka leworęcznego ?','maniak','manierysta','malwersant','mańkut','d','10'),
('Kamizelka ratunkowa to:','kapłon','kapok','kabłąk','kabura','b','10'),
('Klepsydra to urządzenie, w którym czas odmierzany jest przez:','piasek','wskazówki','światło','ziarna prosa','a','10'),
('Które z wymienionych państw nie leży w Afryce ?','Kolumbia','Maroko','Algieria','Egipt','a','10'),
('Jak nazywa się część korzenia włosa ?','bulwa','kłącze','cebulka','karpa','c','10'),
('Które z określeń nie oznacza twarzy ?','gors','fizjonomia','facjata','gęba','a','10'),
('Oficjalne posłuchanie udzielone komuś przez osobę na wysokim stanowisku to:','rezolucja','audiencja','audytorium','atrybucja','b','10'),
('Milenium to okres:','10 lat','100 lat','500 lat','1000 lat','d','10'),
('Jakiego człowieka określamy mianem „łazika” ?','pracownika łaźni','wielbiciela Łazuki','lubiącego łazanki','wałęsającego się','d','10'),
('Jak nazywa się kot Gargamela z serialu animowanego pt. „Smerfy” ?','Klakier','Bonifacy','Mamrotek','Filemon','a','10'),
('Brukselka jest odmianą:','śliwy','gruszy','kapusty','fasoli','c','10'),
('Co łagodzi wstrząsy podczas jazdy samochodem ?','poduszka powietrzna','rozrusznik','chłodnica','resory','d','10'),
('Co jest strojem sędziego ?','toga','sutanna','kitel','kombinezon','a','10'),
('Który z owadów wydaje charakterystyczne dźwięki zwane „cykaniem” ?','komar','mucha','świerszcz','pszczoła','c','10'),
('Kajzerka jest rodzajem:','mąki','chleba','ciastka','bułki','d','10'),
('Jaki symbol chemiczny ma tlen ?','Ca','O','Fe','H','b','10'),
('Co jest głównym składnikiem risotto ?','ziemniaki','kasza','ryż','makaron','c','10'),
('W jakiej strefie klimatycznej znajduje się Polska? ','równikowej','zwrotnikowej','podzwrotnikowej','umiarkowanej','d','10'),
('Paparazzi to natrętni:','fotoreporterzy','akwizytorzy','kaznodzieje','kieszonkowcy','a','10'),
('Przez ile nocy Szeherezada opowiadała królowi Szahrijarowi swoje baśnie ?','przez sto dwie','przez siedemset','przez osiemset','przez tysiąc i jedną','d','10'),
('„Gdzie kota nie ma, tam harcują...” :','myszy','chomiki','stonki','karaluchy','a','10'),
('Jak nazywała się karczma, w której diabeł zdybał Twardowskiego ?','Neapol','Rzym','Turyn','Wenecja','b','10'),
('Jakiego koloru jest ugotowany rak ?','zielonego','czerwonego','fioletowego','niebieskiego','b','10'),
('Miecz koronacyjny królów Polski to:','Szczerbiec','Zerwikaptur','Scyzoryk','Glorius','a','10');



INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Co oznacza nazwa „frutti di mare” ?','owoce morza','owoce cytrusowe','owoce leśne','owoce tropikalne','a','20'),
('W jaki dzień tygodnia Robinson Crusoe spotkał swego towarzysza niedoli ?','w poniedziałek','w środę','w czwartek','w piątek','d','20'),
('Co, według Biblii, było białe jak ziarno kolendra i miało smak placka z miodem ?','ambrozja','manna','rosa niebieska','nektar','b','20'),
('Przedmiot sporu to inaczej:','kość niezgody','cierń niezgody','ość niezgody','szydło z worka','a','20'),
('Wielokątem o najmniejszej liczbie boków jest:','trapez','kwadrat','trójkąt','romb','c','20'),
('Jakiego koloru owoce ma jarzębina ?','czarnego','czerwonego','fioletowego','białego','b','20'),
('Garncarz wytwarza naczynia:','z gliny','z drewna','z metalu','ze szkła','a','20'),
('Ilu długościom promienia danego okręgu jest równa jego średnica ?','jednej','dwóm','trzem','czterem','b','20'),
('O kimś, kto przeliczył się z własnymi siłami, mówimy, że „porwał się na Słońce” :','z łopatą','z parasolką','z motyką','z grabiami','c','20'),
('Która z podanych liczb jest podzielna przez 3 ?','11','18','26','32','b','20'),
('Człowiek „przesadnie religijny” jest nazywany:','bigamistą','biblistą','bigotem','bikiniarzem','c','20'),
('Tłusty Czwartek to ostatni czwartek:','postu','adwentu','karnawału','roku kalendarzowego','c','20'),
('Cienki papier powleczony z jednej strony farbą, służący do odbijania pisma to:','welin','kalka','celofan','bumaga','b','20'),
('Odmianą jakiej rośliny jest jasiek ?','grochu','fasoli','kapusty','kukurydzy','b','20'),
('Pieśń żeglarzy śpiewana przez nich w rytm pracy to:','szanta','pean','chanson','protest song','a','20'),
('„Persona non grata” to:','osoba niepożądana','dusza towarzystwa','osoba nieobecna','osoba niepunktualna','a','20'),
('Kompozycja ułożona z kawałków kolorowego szkła, zespolonych ołowianymi ramkami to:','wizjer','witraż','witryna','witriol','b','20'),
('Przez jaki kontynent wędrują Staś i Nel w powieści Henryka Sienkiewicza pt. „W pustyni i w puszczy” ?','Azję','Amerykę Północną','Australię','Afrykę','d','20'),
('Chronologiczny zapis wydarzeń z życia państwa lub instytucji to:','notatnik','brulion','kronika','pamiętnik','c','20'),
('Osoba chodząca w czasie snu to:','dyslektyk','heretyk','diabetyk','lunatyk','d','20'),
('Paź królowej jest:','biedronką','motylem','świerszczem','pszczołą','b','20'),
('Jakiego koloru kwiaty ma konwalia majowa ?','białe','fioletowe','pomarańczowe','czerwone','a','20'),
('Gdzie powstał pierwszy klub piłki nożnej ?','w USA','w Anglii','w Holandii','w Japonii','b','20'),
('Jak nazywa się towarzysz podróży Poldka w filmie pt. „Podróż za jeden uśmiech” ?','Mandaryn','Duduś','Pikador','Tolek','b','20'),
('Rodzaj przenośnej ścianki złożonej z kilku ruchomych skrzydeł, połączonych zawiasami to:','parawan','zazdrostka','kontuar','bufet','a','20'),
('Dać komuś nauczkę to „pokazać, gdzie raki...” :','nocują','zimują','czmychają','kończą','b','20'),
('W pobliżu jakiego miasta znajduje się Puszcza Kampinoska ?','Wrocławia','Augustowa','Warszawy','Kalisza','c','20'),
('Opłata pobierana przez państwo od przywozu i wywozu towarów na jego granicy to:','cło','porto','frycowe','haracz','a','20'),
('Jak nazywa się sztuka pięknego pisania ?','ortografia','kartografia','ortoepia','kaligrafia','d','20'),
('Imię męskie lub mała poduszka pod głowę to:','jasiek','rysiek','grzesiek','stasiek','a','20'),
('Stolicą jakiego państwa jest Oslo ?','Danii','Szwecji','Belgii','Norwegii','d','20'),
('Kiedy chcemy do kogoś mówić po imieniu, pijemy z nim:','karniak','bruderszaft','strzemienne','zwischenruf','b','20'),
('Narodowym sportem Japonii jest:','jazda figurowa','piłka nożna','sumo','skoki narciarskie','c','20'),
('Która z postaci z dobranocek nie jest misiem ?','Puchatek','Kłapouchy','Coralgol','Uszatek','b','20'),
('Ile razy w Polsce odbyły się letnie Igrzyska Olimpijskie ?','ani razu','jeden raz','dwa razy','trzy razy','a','20'),
('Które z orzechów są najmniejsze ?','kokosowe','włoskie','brazylijskie','pistacjowe','d','20'),
('Mówimy, że „Przyszła kryska na...” :','Zbyszka','Franciszka','Matyska','Ryśka','c','20'),
('W boksie „garda” oznacza:','cios od dołu','cios prawą ręką','klincz','osłonę przed ciosem','d','20'),
('Które zwierzęta po szkoleniu służą ociemniałym jako przewodnicy ?','chomiki','psy','sokoły','koty','b','20'),
('Serek rodem z Podlasia to:','oscypek','ementaler','camembert','feta','a','20'),
('W restauracji stolik obsługuje:','klezmer','kelner','klakier','krupier','b','20'),
('Pasożyt wśród pajęczaków, postrach turystów w okresie letnim to:','topik','kosarz','kleszcz','skorpion','c','20'),
('Sportowców jakiej dyscypliny sportu nazywa się szczypiornistami ?','rzutu oszczepem','skoku o tyczce','piłki ręcznej','golfa','c','20'),
('Odmianą gruszy nie jest:','klapsa','bera','renkloda','konferencja','c','20'),
('Z jakim stworzeniem kojarzy się koncha ?','z gąbką','ze ślimakiem','z rozgwiazdą','z krewetką','b','20'),
('Na jakie miasto spadła pierwsza bomba atomowa ?','na Tokio','na Osakę','na Jokohamę','na Hiroszimę','d','20'),
('Jeśli jesteśmy zadowoleni z obsługi w kawiarni, do rachunku doliczamy:','popiwek','podpiwek','napiwek','napitek','c','20'),
('Władze jakiego państwa utworzyły w 1831 roku Legię Cudzoziemską ?','Francji','Węgier','Japonii','Bułgarii','a','20'),
('W jakim mieście odbywał się Festiwal Piosenki Żołnierskiej ?','w Opolu','w Sopocie','we Wrocławiu','w Kołobrzegu','d','20'),
('Charakterystycznym odgłosem wydawanym przez bociany jest:','klekot','kląskanie','świergot','klangor','a','20'),
('Mówić rzeczy zmyślone to „pleść...” :','koszałki-opałki','koszałki-niedopałki','koszałki-rozpałki','koszałki-podpałki','a','20'),
('Tradycyjny strój japoński to:','peplos','kimono','sari','sarong','b','20'),
('Naczynie do podlewania roślin, zaopatrzone w sitko to:','durszlak','cebrzyk','konewka','kwarta','c','20'),
('Biceps jest mięśniem:','ramienia','brzucha','łydki','uda','a','20'),
('Ile godzin liczą dwie doby ?','12','24','38','48','d','20'),
('Inna nazwa kometki to:','polo','pelota','badminton','krykiet','c','20'),
('Jakie urządzenie potocznie nazywamy „korkiem” ?','licznik','bezpiecznik','dzwonek','kontakt','b','20'),
('Który z komiksowych Galów odznaczał się niespotykaną siłą ?','Asterix','Panoramix','Ideefix','Obelix','d','20'),
('Ręczny warsztat tkacki to:','kołowrotek','krosno','kalander','wrzeciono','b','20'),
('Które z imion nie jest  związane z trzema przysłowiowymi „zimnymi ogrodnikami” ?','Horacy','Bonifacy','Pankracy','Serwacy','a','20'),
('Kim w mitologii greckiej był Cerber ?','jednym z cyklopów','potworem morskim','bogiem wojny','piekielnym psem','d','20'),
('Co chroni palec przy szyciu ręcznym przed ukłuciami igły ?','nawlekacz','szydełko','naparstek','mitenka','c','20'),
('Z jakiego mięsa robi się tatara ?','z baraniny','z wieprzowiny','z drobiu','z wołowiny','d','20'),
('Pies, który przemierzył pół kraju, aby dotrzeć do poprzednich właścicieli to:','Beethoven','Lassie','Goofy','Pluto','b','20'),
('Przy jakiej granicy leży Cieszyn ?','z Niemcami','z Czechami','ze Słowacją','z Ukrainą','b','20'),
('Robert Korzeniowski jest znanym:','narciarzem','chodziarzem','piłkarzem','baloniarzem','b','20'),
('W którym z wymienionych krajów obowiązuje lewostronny ruch drogowy ?','w Czechach','na Węgrzech','w Wielkiej Brytanii','w Belgii','c','20'),
('Narządem oddechowym większości ryb są:','płuca','skrzela','pęcherze pławne','płucotchawki','b','20'),
('Specjalista od chorób serca to:','kardiolog','geriatra','ortopeda','endokrynolog','a','20'),
('Które z niemieckich miast dzielił zburzony w 1989 roku mur ?','Bonn','Kolonię','Monachium','Berlin','','20'),
('Jakie zwierzę występuje w bajkach w roli chytruska ?','sowa','zając','lis','kruk','c','20'),
('Jak nazywają się aromatyczne, brązowe ciastka z Torunia ?','obwarzanki','krakersy','pierniki','markizy','c','20'),
('Seweryn Krajewski był liderem zespołu:','Czerwone Gitary','Alibabki','Anawa','Dwa Plus Jeden','a','20'),
('Jak miał na imię król Sobieski ?','Bolesław','Władysław','Jan','Kazimierz','c','20'),
('Czego nie potrzebujemy do sporządzenia sosu winegret ?','oliwy','cynamonu','octu','soli','b','20'),
('Który z wymienionych węży jest dusicielem ?','kobra','grzechotnik','boa','mamba','c','20'),
('Okrycie wierzchnie w kształcie kwadratu z wyciętym na środku otworem na głowę to:','poncho','pelisa','bolerko','salopa','a','20'),
('Co służy do kreślenia tuszem linii na powiece lub wokół oka ?','konturówka','mascara','korektor','eye-liner','d','20'),
('Jak nazywa się sucha, twarda kiełbasa z nalotem z pleśni ?','mortadela','salami','metka','frankfurter','b','20'),
('Myszka jest elementem wyposażenia:','telewizora','telefonu','telefaksu','komputera','d','20'),
('Na rynku którego z miast w południe możemy oglądać koziołki ?','Krakowa','Wrocławia','Poznania','Warszawy','c','20'),
('Który z wymienionych owoców ma zielony miąższ ?','pomarańcza','arbuz','jagoda','kiwi','d','20'),
('Dziecięcy oddział szpitalny to:','interna','pediatria','geriatria','gastroenterologia','b','20'),
('W jakim miesiącu obchodzimy Dzień Zakochanych ?','w styczniu','w lutym','w kwietniu','w maju','b','20'),
('Gdzie przesiadywał leń z wiersza Jana Brzechwy ?','w fotelu','na podłodze','na tapczanie','na werandzie','c','20'),
('Jak nazywała się małpka należąca do Pippi Langstrumpf, przesiadująca na jej ramieniu ?','Tytus','King Kong','pan Nielson','Zyta','c','20'),
('Za pomocą magnetofonu odtwarzamy dźwięk:','z płyt kompaktowych','z kaset','z płyt analogowych','z dyskietek','b','20'),
('Ile państw powstało w wyniku rozpadu Czechosłowacji ?','2','3','4','5','a','20'),
('Owoce której z roślin nie są kuliste ?','kawona','patisona','wiśni','moreli','b','20'),
('Które z miast jest położone najbardziej na południe ?','Wrocław','Gdańsk','Kalisz','Zakopane','d','20'),
('Z jakim turniejem kojarzy się Roland Garros ?','szachowym','brydżowym','tenisowym','skoków narciarskich','c','20'),
('Który z narządów człowieka nie jest parzysty ?','nerki','jajniki','płuca','dwunastnica','d','20'),
('Jak nazywa się kopalna żywica z drzew iglastych z trzeciorzędu ?','agat','bursztyn','topaz','perła','b','20'),
('Które z wymienionych zwierząt nie występuje w Afryce w warunkach naturalnych ?','żyrafa','lew','zebra','panda wielka','d','20'),
('Czym jest sorbet ?','zupą','ciastem','ostrym sosem','deserem','d','20'),
('Jak nazywał się kapitan z książki Julesa Verne pt. „20.000 mil podmorskiej żeglugi” ?','Hook','Nemo','Grant','Sindbad','b','20'),
('Jaką częścią mowy jest słowo „zielony” ?','przysłówkiem','przymiotnikiem','rzeczownikiem','czasownikiem','b','20');



INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Sport wodny uprawiany na desce z żaglem to:','skateboard','surfing','windsurfing','bojery','c','30'),
('Kto był prezydentem Rzeczypospolitej Polskiej bezpośrednio przed Lechem Wałęsą ?','Czesław Kiszczak','Mieczysław Rakowski','Wojciech Jaruzelski','Aleksander Kwaśniewski','c','30'),
('Urządzenie służące do nagrywania i odtwarzania wiadomości w telefonie komórkowym to:','toner','faks','poczta głosowa','poczta elektroniczna','c','30'),
('Powłoka na naczyniach kuchennych zapobiegająca przywieraniu potraw to:','poliester','teflon','akryl','winyl','b','30'),
('Bohaterem jakiej powieści Henryka Sienkiewicza jest Jurand ze Spychowa ?',' „W pustyni i w puszczy”','„Quo Vadis”','„Potop”','„Krzyżacy”','d','30'),
('Kto został wiceprezesem Polskiego Związku Piłki Nożnej w 1999 roku ?','Grzegorz Lato','Zbigniew Boniek','Roman Kosecki','Jan Tomaszewski','b','30'),
('Napój Anglików pijany tradycyjnie o piątej po południu to:','oranżada','kakao','herbata','whisky','c','30'),
('W której z wymienionych dziedzin algi znalazły szerokie zastosowanie ?','w budownictwie','w kosmetyce','w obuwnictwie','w dziewiarstwie','b','30'),
('Wywar rosołowy to:','bulion','żur','wassersuppe','bulion Ureya','a','30'),
('Flausz to tkanina używana na:','bluzki','fartuchy','płaszcze','halki','c','30'),
('Jaki problem miał Słoń Trąbalski z wiersza Juliana Tuwima ?','był zapominalski','był kłamczuchem','był nietowarzyski','był rozrzutny','a','30'),
('Daszek z wyciągiem umieszczony nad kuchnią, służący do usuwania zapachów na zewnątrz to:','lufcik','wywietrznik','okap','szyber','c','30'),
('Jakie imię nosi największy dzwon w Polsce ?','August','Zygmunt','Kazimierz','Bolesław','b','30'),
('Który z poetów polskich pisał: „O szyby deszcz dzwoni, deszcz dzwoni jesienny” ?','Jan Kasprowicz','Leopold Staff','Jan Lechoń','Julian Tuwim','b','30'),
('W jakich jednostkach mierzy się długość i szerokość geograficzną ?','godzinach i minutach','metrach','stopniach i minutach','milach','c','30'),
('Bawaria jest państwem związkowym:','Francji','Holandii','Niemiec','Czech','c','30'),
('Jakie urządzenie służy do wykrywania, zapisywania i badania trzęsień ziemi ?','polarymetr','aerograf','spektrometr','sejsmograf','d','30'),
('Zbieranie z powierzchni rosołu ściętego białka to:','szumowanie','peklowanie','szpikowanie','marynowanie','a','30'),
('Kto był gospodarzem Mistrzostw Europy w piłce nożnej w 2000 roku ?','Francja','Włochy','Holandia i Belgia','Niemcy','c','30'),
('Twórcą jakiego imperium był Czyngis-chan ?','japońskiego','chińskiego','tatarskiego','mongolskiego','d','30'),
('Podwiązki służą do podtrzymywania:','rajstop','pończoch','spodni','rajtuzów','b','30'),
('Nieprofesjonalny wykonawca roli aktorskiej w filmie to:','naturalista','kinoman','dubler','naturszczyk','d','30'),
('Pulchne placki drożdżowe smażone na oleju to:','knedle','naleśniki','racuchy','podpłomyki','c','30'),
('Janusz Kofta śpiewał, aby pamiętali:','o pomnikach','o kwiatach','o najbliższych','o ogrodach','d','30'),
('Jak inaczej określa się osobę chorą na cukrzycę ?','diabetyk','dyslektyk','homeopata','dietetyk','a','30'),
('Który z wymienionych metali wykorzystywany jest w termometrach ?','rubid','rod','rtęć','ruten','c','30'),
('Statek wodny, na którego pokładzie mogą startować i lądować samoloty to:','tankowiec','krążownik','niszczyciel','lotniskowiec','d','30'),
('Czworokąt, którego wszystkie boki są równe oraz wszystkie kąty proste to:','prostokąt','kwadrat','romb','trapez','b','30'),
('Czego nie oznacza nazwa „koziorożec” ?','znaku zodiaku','zwrotnika','sera z koziego mleka','kozła skalnego','c','30'),
('Gorące źródło wyrzucające w regularnych odstępach czasu wodę i parę wodną to:','wulkan','gejzer','bojler','źródło artezyjskie','b','30'),
('Uszy którego ze zwierząt w gwarze myśliwskiej nazywane są „słuchami” ?','tarpana','żaby','sarny','zająca','d','30'),
('Piaszczyste wzniesienie usypane przez wiatr to:','piarg','firn','wydma','kopiec','c','30'),
('W jakim mieście znajduje się słynny 102-piętrowy wieżowiec Empire State Building ?','w Londynie','w Nowym Jorku','w Sydney','w Ottawie','b','30'),
('Ptak wykorzystywany przez wojsko od starożytności do II wojny światowej do przenoszenia wiadomości to:','bocian','jastrząb','gołąb','dzika gęś','c','30'),
('W jakich jednostkach mierzymy natężenie dźwięku ?','w decybelach','w lumenach','w kelwinach','w amperach','a','30'),
('Depresja to obszar położony:','1000 m n.p.m.','500 m n.p.m.','na poziomie morza','poniżej poziomu morza','d','30'),
('Haftka to rodzaj:','ściegu','agrafki','suwaka','zapinki','d','30'),
('Miękka czapka wojskowa bez daszka, podłużnie składana to:','rogatywka','panama','maciejówka','furażerka','d','30'),
('Nad jaką zatoką leży Półwysep Westerplatte ? ','Zatoką Gdańską','Zatoką Meklemburską','Zatoką Pomorską','Zatoką Ryską','a','30'),
('Ostatni przypadek w deklinacji polskiej to:','wołacz','narzędnik','miejscownik','biernik','a','30'),
('Z jakiego tworzywa robiono okaryny ?','ze stali','z miedzi','z gliny','z bakelitu','c','30'),
('Postać z włoskiej „commedia dell’ arte”, sprytna pokojówka, ukochana Arlekina to:','Pulcinella','Brighella','Scaramuccia','Kolombina','d','30'),
('Na co „za komuny” nie było kartek ?','na „Trybunę Ludu”','na mięso','na cukier','na buty','a','30'),
('Jak nazywa się najwyższa skocznia narciarska ?','żyrafia','słoniowa','mamucia','żurawia ','c','30'),
('Ile wysokości ma stożek ?','jedną','dwie','trzy','cztery','a','30'),
('Litera „Ą” jest:','samogłoską ustną','samogłoską nosową','spółgłoską dźwięczną','spółgłoską bezdźwięczną','b','30'),
('Kto przez 5 lat mieszkał w wozie cyrkowym we wsi Podgradowice ?','Jan Kiliński','Andrzej Lepper','Michał Drzymała','Jan Kierdziołek','c','30'),
('Woltyżerka to ćwiczenia akrobatyczne na koniu, biegnącym po obwodzie:','kwadratu','prostokąta','trójkąta','koła','d','30'),
('Który z zespołów wylansował piosenkę pt. „Bal wszystkich świętych” ?','Myslovitz','T. Love','Budka Suflera','Piersi','c','30'),
('Który z wymienionych dokumentów dotyczy samochodu ?','dowód tożsamości','REGON','resurs','dowód rejestracyjny','d','30'),
('O kimś bez czupryny mówimy:','łysy jak pośladek','łysy jak pięta','łysy jak kolano','łysy jak łokieć','c','30'),
('Ile było krasnoludków w bajce o Królewnie Śnieżce ?','siedmiu','ośmiu','dziewięciu','dziesięciu','a','30'),
('Którą z potraw jadamy na ciepło ?','auszpik','melbę','gulasz','sorbet','c','30'),
('Która z wymienionych liter jest czwartą literą w alfabecie greckim ?','delta','lambda','sigma','omega','a','30'),
('Gody ryb to:','toki','ruja','tarło','ciągi','c','30'),
('Co nie odmierza czasu ?','gnomon','klepsydra','zegar','kampanila','d','30'),
('Który z podanych wyrazów nie określa figury w akrobacjach lotniczych ?','pętla','korkociąg','otwieracz','beczka','c','30'),
('Kląć, mówić ordynarnie to inaczej:','rzucać kamieniem','rzucać mięsem','mieszać błoto','wylewać pomyje','b','30'),
('Ile trwa adwent – w chrześcijaństwie: okres przygotowań do Bożego Narodzenia ?','2 tygodnie','3 tygodnie','4 tygodnie','pół roku','c','30'),
('Rodło – znak rodowy Polaków w Niemczech w stylizowanej formie odtwarza:','bieg Odry','bieg Wisły','bieg Łaby','bieg Renu','b','30'),
('W którym kraju zachęca się rodziny do posiadania tylko jednego potomka ?','w Rosji','w Szwecji','we Francji','w Chinach','d','30'),
('W biegu z przeszkodami zawodnicy skaczą przez:','kozła','mur','żywopłot','płotki','d','30'),
('Przesądni odpukują w:','szklaną kulę','czoło czarnego kota','talię kart','niemalowane drewno','d','30'),
('Półprosta wychodząca z wierzchołka kąta płaskiego i dzieląca go na dwie równe części to:','dwusieczna','średnica','krzywa','cięciwa','a','30'),
('Który z wymienionych ptaków nie jest gatunkiem sowy ?','puchacz','puszczyk','świstun','pójdźka','c','30'),
('W gwarze góralskiej człowiek z nizin to:','cep','kociuba','ceper','cyntuś','c','30'),
('Biathlonista ma na nogach:','narty biegowe','snowboard','narty zjazdowe','narty skokowe','a','30'),
('Potrawa z drobnych klusek gotowanych na mleku lub wodzie to:','zalewajka','zacierka','zasmażka','mamałyga','b','30'),
('Ogary są psami:','pasterskimi','obronnymi','gończymi','pociągowymi','c','30'),
('Jaki okrzyk wydawał kucharz Bartolini Bartłomiej, bohater dobranocki pt. „Porwanie Baltazara Gąbki” ?',' „Mamma Mia!”','„Carramba!”','„Kruca fuks!”','„Ach, jooo!”','a','30'),
('Sok z jakich owoców musi wypić osoba dekorowana Orderem Uśmiechu ?','z czarnej porzeczki','z cytryny','z gruszki','z marchwi','b','30'),
('Jaki kształt mają piramidy w Egipcie ?','walca','graniastosłupa','ostrosłupa','prostopadłościanu','c','30'),
('Krajem przodującym w hodowli tulipanów i ich cebul jest:','Holandia','Belgia','Francja','Szwecja','a','30'),
('Który z kamieni nie należy do szlachetnych ?','nefryt','szmaragd','szafir','rubin','a','30'),
('Określony odcinek wyścigu kolarskiego to:','etap','gem','tercja','runda','a','30'),
('Mieszkańcem rafy koralowej nie jest:','ośmiornica','ciernik','rozgwiazda','gąbka','b','30'),
('Kto był wokalistą zespołu Led Zeppelin ?','Robert Plant','John Lennon','Mick Jagger','Eric Burdon','a','30'),
('Popularna gra planszowa z kostką i płytkami z umieszczonymi na nich literami to:','Domino','Lotto','Scrabble','Monopol','c','30'),
('Co nie należy do ekwipunku płetwonurka ?','maska','raki','butla z tlenem','płetwy','b','30'),
('W piłce nożnej pierwsza żółta kartka pokazana przez sędziego głównego oznacza:','wykluczenie z gry','ostrzeżenie','spalony','zmianę zawodnika','b','30'),
('Afrykański instrument muzyczny umożliwiający przekazywanie sygnałów na odległość to:','tam-tam','drumla','gong','ksylofon','a','30'),
('Posąg Nike z Samotraki posiada:','głowę','ręce','miecz','skrzydła','d','30'),
('Jaka postać nie została stworzona przez Walta Disneya ?','Pszczółka Maja','Goofy','Pluto','Kaczor Donald','a','30'),
('Znaki drogowe w kształcie trójkąta, żółte z czerwonym obrzeżem to  znaki:','zakazu','nakazu','ostrzegawcze','informacyjne','c','30'),
('Na stadionie, a nie nad wodą, odbywają się zawody wędkarstwa:','springowego','spławikowego','podlodowego','rzutowego','d','30'),
('Zgodnie z przesądem, małżeństwo będzie udane, jeśli panna młoda do ślubu założy:','coś niemodnego','coś pożyczonego','coś podartego','coś czarnego','b','30'),
('Który z polskich polityków nie był premierem ?','Tadeusz Mazowiecki','Waldemar Pawlak','Zofia Kuratowska','Jan Krzysztof Bielecki','c','30'),
('Która z wymienionych liczb jest podzielna przez 4 ?','26','36','42','66','b','30'),
('Jaka kopalnia znajduje się w Wieliczce ?','kopalnia soli','kopalnia diamentów','kopalnia miedzi','kopania węgla kamiennego','a','30'),
('Który z motyli jest motylem nocnym ?','paź królowej','cytrynek','pawik grabówka','bielinek kapustnik','c','30'),
('Kto był wokalistą zespołu The Doors ?','Jim Morrison','Jimi Hendrix','Eric Clapton','Elvis Presley','a','30'),
('Jakiej narodowości jest Nadia Comaneci, 5-krotna mistrzyni olimpijska ?','bułgarskiej','węgierskiej','rumuńskiej','czeskiej','c','30');



INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Kanał Sueski stanowi umowną granicę między:','Amerykami','Afryką i Azją','Australią i Azją','Kanadą i Grenlandią','b','50'),
('Jak w krawiectwie nazywa się rodzaj zapięcia działającego na zasadzie wtyczki i gniazda ?','zatrzask','rzep','suwak','haftka','a','50'),
('W którym filmie Romana Polańskiego, Mia Farrow spodziewa się dziecka diabła ?',' „Lokator”','„Wstręt”','„Matnia”','„Dziecko Rosemary”','d','50'),
('Kim według mitów greckich byli cyklopi ?','żeglarzami','władcami mórz','jednookimi olbrzymami','bogami','c','50'),
('Kto stoi na czele korpusu dyplomatycznego akredytowanego w danym państwie ?','dziekan','dyrektor','rektor','minister','a','50'),
('Konik morski to:','szkarłupień','ryba','mięczak','głowonóg','b','50'),
('Sprawy codzienne, przyziemne to:','chleb kamienny','chleb świętojański','chleb żałobny','chleb powszedni','d','50'),
('Gdzie w 1963 roku zastrzelono J. F. Kennedy’ego ?','w Los Angeles','w Dallas','w Atlancie','w Phoenix','b','50'),
('W jaki sposób do lata zmierzała wokalistka zespołu Bajm – Beata Kozidrak ?','piechotą','kajakiem','autostopem','hulajnogą','a','50'),
('Ilu było jeźdźców Apokalipsy ?','dwóch','trzech','czterech','pięciu','c','50'),
('Która z podanych miar nie jest stosowana na morzu ?','piędź','węzeł','rumb','kabel','a','50'),
('Jaki numer nosił Rudy – czołg „Czterej pancernych” ?','101','102','202','303','b','50'),
('Starożytni Rzymianie, mówiąc „mare nostrum” (nasze morze), mieli na myśli:','Morze Kaspijskie','Morze Czarne','Morze Czerwone','Morze Śródziemne','d','50'),
('Którą z wymienionych książek dla dzieci napisał Jan Brzechwa ?','Król Maciuś I','Akademia Pana Kleksa','Biały Kieł','Dzieci z Bullerbyn','b','50'),
('Ile kadłubów ma katamaran ?','jeden','dwa','trzy','cztery','b','50'),
('Kim był Sindbad z „Baśni tysiąca i jednej nocy” ?','sułtanem','kupcem','błaznem sułtana','czarownikiem','b','50'),
('Jaki płacz oznaczają „krokodyle łzy” ?','szczery','dyskretny','histeryczny','nieszczery','d','50'),
('Ku czci jakiej bogini wzniesiono Partenon na Akropolu ateńskim ?','Ateny','Artemidy','Demeter','Hery','a','50'),
('Nauczyciel języka obcego na wyższej uczelni to:','adiunkt','lektor','dziekan','docent','b','50'),
('Wirtuozem gry na jakim instrumencie był Niccolo Paganini ?','na waltorni','na skrzypcach','na fortepianie','na harfie','b','50'),
('Legendarny stwór o ciele uskrzydlonego lwa, głowie i szponach orła to:','Gryf','Sfinks','Centaur','Minotaur','a','50'),
('Jak nazywa się znak w notacji  muzycznej obniżający dźwięk o pół tonu ?','synkopa','krzyżyk','bemol','fermata','c','50'),
('Piana z białek rozbita z cukrem i zapieczona w słodkie, białe ciastko to:','makagigi','strudel','ptyś','beza','d','50'),
('Bez której z wymienionych przypraw nie może się obejść grzane wino ?','bez chili','bez cynamonu','bez piołunu','bez curry','b','50'),
('Wianek panny młodej ozdobiony był dawniej:','anyżkiem','rutą','miętą','macierzanką','b','50'),
('Które z podanych spodni są najdłuższe ?','dzwony','szorty','pludry','bermudy','a','50'),
('Które z podanych miast leży nad Dunajem ?','Nowy Targ','Nowy Sad','Nowy Sącz','Nowy Staw','b','50'),
('Szkarlatyna to inaczej:','koklusz','grypa','płonica','malaria','c','50'),
('Czego nie produkują pszczoły ?','mleczka','kitu','wosku','nektaru','d','50'),
('Kto porwał Piękną Helenę w utworze Homera pt. „Iliada” ?','Agamemnon','Achilles','Parys','Hektor','c','50'),
('Kim był Louis Armstrong ?','trębaczem jazzowym','astronautą','pisarzem','konstruktorem','a','50'),
('Jakie zwierzęta wyposażone są w kądziołki ?','nietoperze','kameleony','modliszki','pająki','d','50'),
('Co nie jest ogrodzeniem ?','ostrokół','palisada','zarzuela','zeriba','c','50'),
('Jakiego rodzaju artylerii użyli prawdopodobnie Krzyżacy w bitwie pod Grunwaldem ?','haubic','bombard','zenitówek','pancerzownic','b','50'),
('Od końca XIX wieku kwintal liczył:','10 kg','100 kg','150 kg','200 kg','b','50'),
('Co przypomina odgłos wydawany przez hienę ?','mlaskanie','chichot','mruczenie','sapanie','b','50'),
('Powiedzenie „dziesiąta woda po kisielu” oznacza:','mdły smak','coś bardzo rzadkiego','odległe pokrewieństwo','coś niesmacznego','c','50'),
('Ile „ramion” ma ośmiornica ?','trzy','pięć','osiem','dwanaście','c','50'),
('W jakiej dyscyplinie sportowej Artur Partyka zdobył tytuł mistrza Europy w 1998 roku ?','w skoku w wzwyż','w pchnięciu kulą','w żeglarstwie','w judo','a','50'),
('Z jakim ssakiem spokrewniony jest bizon ?','z jeleniem','z łosiem','z sarną','z żubrem','d','50'),
('Jakiego koloru jest łódź podwodna w piosence zespołu The Beatles ?','białego','czarnego','żółtego','niebieskiego','c','50'),
('W jakim mieście znajduje się Ściana Płaczu ?','w Rzymie','w Pekinie','w Bombaju','w Jerozolimie','d','50'),
('Jakie lotnictwo zaatakowało Pearl Harbor 7 grudnia 1941 roku ?','radzieckie','włoskie','japońskie','niemieckie','c','50'),
('W jakim kraju wynaleziono klocki Lego ?','w USA','w Danii','w Niemczech','na Węgrzech','b','50'),
('W jakim budynku gospodarczym Augiasz miał największy bałagan ?','w kurniku','w chlewni','w stodole','w stajni','d','50'),
('Bohaterem jakiej sztuki Bertolta Brechta jest Mackie Majcher ?',' „Matka Courage”','„Kariera Artura Uli”','„Życie Galileusza”','„Opera za 3 grosze”','d','50'),
('Jakiego zawodu uczy się bohaterka grana przez Jodie Foster w filmie pt. „Milczenie owiec” ?','agentki FBI','modelki','barmanki','adwokata','a','50'),
('Latimeria to:','ryba trzonopłetwa','taniec','hiszpańska potrawa','kobiece imię','a','50'),
('W dramacie Wyspiańskiego na wesele Chochoła zaprasza:','Dziennikarz','Czepiec','Gospodarz','Rachela','d','50'),
('Organizacja światowa zrzeszająca narodowe związki piłkarskie to:','NBA','WBO','WBC','FIFA','d','50'),
('Cichociemni działali w okresie:','powstania styczniowego','potopu szwedzkiego','II wojny światowej','zimnej wojny','c','50'),
('Najbardziej „zakręcona” polska wokalistka to:','Reni Jusis','Maryla Rodowicz','Katarzyna Skrzynecka','Agnieszka Chylińska','a','50'),
('Przeciwieństwem ascety jest:','pokutnik','sybaryta','biczownik','męczennik','b','50'),
('Tak zwana dziura ozonowa to spadek zawartości ozonu:','w oceanach','w litosferze','w atmosferze','w przestrzeni kosmicznej','c','50'),
('Który z podanych terminów nie określa części mózgu ?','błona podstawna','szyszynka','wzgórze','przysadka','a','50'),
('W piłce ręcznej zawodnicy, poza bramkarzem, nie mogą dotykać piłki:','odbitej przez przeciwnika','głową','tułowiem','nogą poniżej kolana','d','50'),
('W wojskach lądowych jedna gwiazdka na pagonie oznacza:','kaprala','chorążego','sierżanta','plutonowego','b','50'),
('Ile naturalnych satelitów ma Ziemia ?','jednego','dwóch','trzech','czterech','a','50'),
('„Nie rzucim ziemi, skąd nasz ród...” – tak zaczyna się:',' „Warszawianka”','„Boże, cos Polskę”','„Pierwsza Brygada”','”Rota”','d','50'),
('Jakiego koloru nie ma na fladze Belgii ?','żółtego','niebieskiego','czarnego','czerwonego','b','50'),
('Urządzenie na pokładzie samolotu, pomagające ustalić przyczyny ewentualnej katastrofy to:','trymer','blue box','czarna skrzynka','wolant','c','50'),
('Symbolem „hi-fi” oznaczamy:','jakość obrazu','jakość dźwięku','estetykę produktu','wysoką cenę','b','50'),
('Wyborcy popierający określoną partię lub kandydata to:','elektorat','publiczność','audytorium','respondenci','a','50'),
('Tytułowy bohater komedii pt. „Miś” jest prezesem klubu:',' „Wisła”','„Słoneczko”','„Tęcza”','„Warszawianka”','c','50'),
('Okresowy sprawdzian wiadomości studenta, najczęściej pisemny to:','referat','wypracowanie','rozprawka','kolokwium','d','50'),
('Jak nazywa się zakonnik pilnujący drzwi w bramie klasztornej ?','eremita','oblat','furtian','cenobita','c','50'),
('Reżyserem tanecznych układów widowisk scenicznych, szczególnie baletowych jest:','choreograf','scenograf','inscenizator','inspicjent','a','50'),
('Co nie służy do kierowania wierzchowcem ?','cugle','lejce','wodze','popręg','d','50'),
('Symbol chemiczny magnezu to:','Mn','Mg','Mo','Md','b','50'),
('Ryszard Riedel śpiewał w zespole:','Budka Suflera','Elektryczne Gitary','Dżem','Kombi','c','50'),
('Który ze znanych dziennikarzy grał postać Dudusia w serialu pt. „Podróż za jeden uśmiech” ?','Tomasz Lis','Wojciech Jagielski','Maciej Orłoś','Filip Łobodziński','d','50'),
('Gdzie w organizmie ludzkim znajduje się plamka ślepa ?','w oku','w mózgu','w sercu','w wątrobie','a','50'),
('Które z owadów nie są pod ochroną w Polsce ?','jelonki rogacze','modliszki zwyczajne','biegacze','bielinki kapustniki','d','50'),
('Bohaterem jakiej powieści jest Cezary Baryka ?',' „Wierna rzeka”','„Popioły”','„Dzieje grzechu”','„Przedwiośnia”','d','50'),
('Norka jakiego zwierzęcia była bramą krainy czarów, do której trafiła Alicja ?','królika','borsuka','nornicy','lisa','a','50'),
('Wywrócenie się samochodu lub samolotu do góry kołami to:','kabotaż','abordaż','sabotaż','kapotaż','d','50'),
('Przedstawiciel dyplomatyczny Watykanu w randze ambasadora to:','kardynał','nuncjusz','regent','arcybiskup','b','50'),
('Która z pań nie była premierem ?','Indira Gandhi','Golda Meir','Margaret Thatcher','Zofia Kuratowska','d','50'),
('Niemiecka moneta zdawkowa to:','grosch','stotinka','cent','pfennig','d','50'),
('Gdzie rozgrywa się akcja musicalu pt. „Evita”, który opowiada historię żony prezydenta Juana Perona ?','w Argentynie','w Chile','w Boliwii','w Hiszpanii','a','50'),
('Karabinek AKM jest zasilany z magazynka:','pudełkowego','talerzowego','bębnowego','integralnego','a','50'),
('W skład jakiego środka stosowanego w gospodarstwie domowym wchodzi chlor ?','płynu do kąpieli','szamponu','pasty do zębów','wybielacza do tkanin','d','50'),
('Chrześcijańska nazwa Stambułu to:','Konstantynopol','Aleksandretta','Nikomedia','Synopa','a','50'),
('Flanka to w terminologii wojskowej:','czoło','awangarda','skrzydło','centrum','c','50'),
('Kalendarz juliański wprowadził:','Cezar','Pompejusz','Neron','Dioklecjan','a','50'),
('Ile watów liczy kilowat ?','10','100','1000','10000','c','50'),
('Żydowski nagrobek to:','dolmen','macewa','mastaba','cenotaf','b','50'),
('Która z podanych wysp ma pochodzenie wulkaniczne ?','Grenlandia','Madagskar','Oahu','Tajwan','c','50'),
('Motocross to wyścig:','samochodowy','motocyklowy','motorowodny','rowerowy','b','50'),
('Pseudonim utworzony przez napisanie nazwiska autora na odwrót, np. Kynsa – Asnyk, to:','ananim','homonim','antonim','anagram','a','50');

INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Andrzej Grubba to wielokrotny medalista:','w siatkówce','w badmintonie','w tenisie stołowym','w tenisie ziemnym','c','100'),
('Do jakiego morza wpływa rzeka Dunaj ?','do Morza Białego','do Morza Żółtego','do Morza Czarnego','do Morza Czerwonego','c','100'),
('Wędzisko jest częścią:','wędki','uzdy','kagańca','sieci rybackiej','a','100'),
('Amerykańska ambasador przy ONZ i pierwsza kobieta na stanowisku sekretarza stanu w USA to:','Hillary Clinton','Madeleine Albright','Rosalind Franklin','Emmeline Pankhurst','b','100'),
('Zamiar wyprzedzania (względnie: omijania) w pojeździe mechanicznym sygnalizowany jest:','światłami stopu','światłami postojowymi','kierunkowskazem','krótkim klaksonem','c','100'),
('Ile prac musiał wykonać Herakles w służbie u Eurysteusza ?','5','9','12','20','c','100'),
('Przełożona żeńskiej służby na dworze królewskim to:','ochmistrzyni','kuchenna','gospodyni','dwórka','a','100'),
('Antonio Vivaldi był nazywany „czerwonym księdzem” ze względu na jego:','lewicowe poglądy','sympatię do Indian','purpurowe stroje','rude włosy','d','100'),
('Na jakim kontynencie znajduje się Patagonia ?','w Ameryce Północnej','w Ameryce Południowej','w Afryce','w Australii','b','100'),
('Papierem wartościowym, upoważniającym do stałego i z góry określonego dochodu, jest:','akcja','weksel in blanco','dywidenda','obligacja','d','100'),
('Do naczelnych nie należą:','lemurowate','wyraki','małpy wąskonose','leniwce','d','100'),
('Do jakiego gatunku należą filmy pt. „Amityville”, „Halloween”, czy „Koszmar z ulicy Wiązów” ?','do komedii','do horroru','do melodramatu','do westernu','b','100'),
('Kazik Staszewski w piosence Kultu śpiewa, że „gdy nie ma dzieci, to jesteśmy...” :','niegrzeczni','niespokojni','leniwi','kłótliwi','a','100'),
('Konkurs Czterech Skoczni to zawody organizowane w skokach:','narciarskich','do wody','o tyczce','spadochronowych','a','100'),
('Kreon skazał Antygonę na:','ścięcie','zamurowanie żywcem','powieszenie','uduszenie','b','100'),
('Dzielnica Nowego Jorku, w obrębie której znajduje się Wall Street to:','Richmond','Queens','Brooklyn','Manhattan','d','100'),
('Na jaki kolor chciał mieć pomalowany świat zespół Dwa Plus Jeden w piosence pt. „Chodź, pomaluj mój świat” ?','na biało i na różowo','na biało i na zielono','na żółto i na zielono','na żółto i na niebiesko','d','100'),
('Pod jaką postacią Zeus uwiódł Ledę ?','złotego deszczu','byka','łabędzia','orła','c','100'),
('Kształt jakiej litery ma bramka w rugby ?','U','Y','H','T','c','100'),
('Miejsce w kościele w kształcie „szafki”, służące do przechowywania Najświętszego Sakramentu to:','prezbiterium','tabernakulum','monstrancja','pendentyw','b','100'),
('Z jabłek produkuje się wódkę zwaną:','cydr','brandy','celvados','arak','c','100'),
('Pierwsze zęby niemowlęcia to:','zęby mądrości','siekacze','trzonowce','kły','b','100'),
('Kiedy obchodzone jest „Halloween” ?','31 września','31 października','31 listopada','31 grudnia','b','100'),
('Do pomiaru napięcia prądu elektrycznego służy:','kalorymetr','woltomierz','częstościomierz','manometr','b','100'),
('Francuskojęzyczną prowincją Kanady jest:','Ontario','Jukon','Quebec','Alberta','c','100'),
('Wielkość, która określa odczyn roztworu to:','pH','kcal','ASO','IQ','a','100'),
('Który z podanych potworów potrafił zabijać ludzi wzrokiem ?','smok wawelski','bazyliszek','lewiatan','Scylla','b','100'),
('W jakim kraju znajduje się znana z uprawy herbaty prowincja Yunnan ?','w Indiach','w Japonii','w Gruzji','w Chinach','d','100'),
('Jak miał na imię Wallenrod, bohater powieści poetyckiej Adama Mickiewicza ?','Konrad','Gustaw','Kordian','Tadeusz','a','100'),
('Pasożyt wewnętrzny kręgowców o ciele wstęgowatym i podzielonym na segmenty to:','glista ludzka','tasiemiec','włosień kręty','przywra','b','100'),
('Pojazd wykonujący na drodze prace remontowe powinien wysyłać sygnały świetlne w kolorze:','żółtym','białym','niebieskim','czerwonym','a','100'),
('Czym pokryte są liście drapieżnej rosiczki ?','lepkimi włoskami','ostrymi kolcami','parzydełkami','śmiertelnym jadem','a','100'),
('Muzyczny styl reggae rozpowszechniony przez Boba Marleya pochodzi:','z Jamajki','z Wielkiej Brytanii','z Cejlonu','z Majorki','a','100'),
('Co trzyma w dziobie kruk w bajce Ignacego Krasickiego pt. „Kruk i Lis” ?','obrączkę','gałązkę','ser','piórko','c','100'),
('Mazagran to nazwa:','religii staroirańskiej ','dzielnicy Budy','napoju','tkaniny na suknie','c','100'),
('Jaki symbol oznacza „świeżo upieczonego” kierowcę ?','wykrzyknik','krzyżyk','czerwone kółko','zielony listek','d','100'),
('Z gry na jakim instrumencie słynie Vanessa Mae ?','na drumli','na oboju','na skrzypcach','na pianinie','c','100'),
('Afrykański kuzyn dzika to:','oryks','dujker','guziec','eland','c','100'),
('Jak nazywał się przywódca największego w starożytności powstania niewolników ?','Milon z Krotonu','Spartakus','Krassus','Pompejusz Wielki','b','100'),
('Przykładem jakiej architektury jest Pałac Kultury i Nauki w Warszawie ?','eklektyzmu','klasycyzmu','modernizmu','socrealizmu','d','100'),
('W którym z wymienionych filmów Stevena Spielberga główny bohater ma ok. siedmiu metrów  długości i mnóstwo ostrych zębów ?',' „E.T.”','„Indiana Jones”','„Szczęki”','„Kolor purpury”','c','100'),
('Kto na ogonie pawia umieścił oczy, zabitego przez Hermesa, stuokiego Argosa ?','Atena','Hera','Hekate','Hestia','b','100'),
('Które z wymienionych państw nie należy do Beneluxu ?','Luksemburg','Belgia','Francja','Holandia','c','100'),
('Trucizna wykorzystywana przez Indian południowoamerykańskich do zatruwania strzał to:','amigdalina','kurara','akonityna','meskalina','b','100'),
('Kogo Posejdon wysłał przeciw Laokoonowi i jego synom za ostrzeżenie Trojan ?','dwa cyklopy','dwie syreny','dwie harpie','dwa węże morskie','d','100'),
('W jakim miejscu rozgrywa się większa część filmu pt. „Gorączka sobotniej nocy” ?','w dyskotece','na basenie','w ZOO','na polu golfowym','a','100'),
('Fort Knox zawiera federalne zapasy:','diamentów','dzieł sztuki','złota','platyny','c','100'),
('Anty-Oscar, nagroda przyznawana w kategoriach filmowych przez Fundację Johna Wilsona to:','Malina','Figa','Banan','Ananas','a','100'),
('Piłkarski przydomek Zbigniewa Bońka to:','Zibi','Kosa','Oli','Cesarz','a','100'),
('O czyim pojedynku opowiada Wojski w powieści Adama Mickiewicza pt. „Pan Tadeusz” ?','Pawła z Gawłem','Doweyki i Domeyką','Lelum z Polelum','Cześnika z Rejentem','b','100'),
('Które z określeń nie jest częścią mikroskopu:','kondensator','tubus','okular','kondensor','a','100'),
('Patronem jakiego kraju jest św. Patryk ?','Niemiec','Irlandii','Austrii','Francji','b','100'),
('Skorupiakiem nie jest:','mangusta','langusta','krewetka','krab','a','100'),
('W jakiej roli wystąpił Tom Cruise w filmie pt. „Top Gun” ?','króla dyskotek','tajnego agenta','pilota marynarki','gangstera','c','100'),
('Do kogo Jan Sobieski pisał pełne miłosnych wyznań listy ?','do Marii Kazimiery','do Delfiny Potockiej','do Marii Walewskiej','do Izabeli Czartoryskiej','a','100'),
('Jak nazywa się namiętność do kłamstwa i przesady ?','monomania','mitomania','piromania','hipomania','b','100'),
('Pałac we Francji, w którym znajduje się jedna z największych kolekcji dzieł sztuki to:','Wersal','Luwr','Pałac Luksemburski','Hotel Lambert','b','100'),
('Jak nazywa się przenośny namiot Mongołów ?','wigwam','koliba','jurta','igloo','c','100'),
('Z ilu atomów tlenu składa się cząsteczka ozonu ?','z jednego','z dwóch','z trzech','z czterech','c','100'),
('Artystycznie wykonany znak własnościowy książki to:','ekslibris','gmerk','kolofon','errata','a','100'),
('Jedynym przedstawicielem płetwonogich, polującym na zwierzęta stałocieplne jest:','mors','lew morski','lampart morski','słoń morski','c','100'),
('Stolicą Litwy jest:','Lwów','Kijów','Wilno','Kowno','c','100'),
('Ile czasu trwa jeden obrót Ziemi wokół własnej osi ?','12 godzin','dobę','tydzień','miesiąc','b','100'),
('Największa organizacja na świecie walcząca na rzecz ochrony środowiska to:','Greenpeace','WHO','UNICEF','UNESCO','a','100'),
('Kto na scenę wprowadził kankana ?','Jacques Offenbach','Ralph Benatzky','Johann Strauss','Karl Zeller','a','100'),
('Która z klęsk najczęściej nawiedza Japonię ?','susza','huragany','trzęsienia ziemi','plagi szkodników','c','100'),
('Z jakiego drzewa zbierane są kwiaty na herbatkę na przeziębienie ?','z klonu','z topoli','z akacji','z lipy','d','100'),
('Bezleśna strefa roślinna w północnej strefie podbiegunowej to:','tundra','selwa','tajga','step','a','100'),
('Które z podanych zwierząt nie zapada w sen zimowy ?','świstak','kuna leśna','jeż','nietoperz nocek','b','100'),
('Śnieżka jest najwyższym szczytem:','Gór Sowich','Gór Bystrzyckich','Karkonoszy','Beskidu Małego','c','100'),
('Wczesna msza odprawiana w adwencie to:','requiem','roraty','nieszpory','Zaduszki','b','100'),
('Piosenką „Private dancer” rozpoczęła solową karierę:','Janet Jackson','Tina Turner','Natalie Cole','Cher','b','100'),
('Czego szukano w czasie Nocy Świętojańskiej ?','kwiatu paproci','garnka z monetami','wody życia','kryształu górskiego','a','100'),
('Który z terminów określa japońską potrawę ?','ikebana','bonsai','manga','sushi','d','100'),
('W którym z wymienionych filmów główną rolę zagrał Michael Douglas ?',' „Indiana Jones”','„Nagi instynkt”','„Maska zorro”','„Park Jurajski”','b','100'),
('Papier-mache jest wykorzystywany do wyrobu:','pieniędzy','papeterii','masek w teatrze','konfetti','c','100'),
('Na terenie jakiego województwa znajduje się Woliński Park Narodowy ?','zachodniopomorskiego','pomorskiego','warmińsko-mazurskiego','kujawsko-pomorskiego','a','100'),
('Jak nazywała się kraina z filmu pt. „Kingsajz”, zamieszkiwana przez krasnale ?','Szuflandia','Oz','Laputa','Taka-Tuka','a','100'),
('Popularny w latach 70-tych XX wieku autobus z Jelcza nazywany był:','cytrynką','garbusem','ogórkiem','trampkiem','c','100'),
('Która z polskich elektrowni nie jest elektrownią wodną ?','Rożnów','Bełchatów','Solina','Włocławek','b','100'),
('Hannibal był wielkim wodzem:','Kartaginy','Rzymu','Macedonii','Wikingów','a','100'),
('Najwyższy stopień wojskowy w marynarce wojennej to:','kapitan marynarki','komandor','admirał','kontradmirał','c','100'),
('Święto Trzech Króli nazywane jest inaczej:','Świętem Dziękczynienia','Świętem Wielkiej Nocy','Świętem Zmarłych','Świętem Objawienia Pańskiego','d','100'),
('W jakim kraju znajduje się Transylwania ?','w Macedonii','na Słowacji','w Rumunii','na Węgrzech','c','100'),
('Dwa młodzieżowe gangi „Jets’ i „Sharks” walczą w musicalu:',' „Hair”','„West Side Story”','„Deszczowa piosenka”','„Yankee Doddle Dandy”','b','100');


INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Kto w latach 1987-1991 pełnił funkcję rzecznika praw obywatelskich ?','Ewa Łętowska','Zofia Kuratowska','Hanna Suchocka','Alicja Grześkowiak','a','200'),
('Kopaliną nie jest:','glina','żwir','margiel','cement','d','200'),
('Jak nazywa się tajna organizacja terrorystyczna Kraju Basków ?','IRA','ETA','Hezbollah','Czerwone Brygady','b','200'),
('Który z piłkarzy na mistrzostwach świata w Meksyku w 1986 roku zdobył gola dzięki „ręce boskiej” ?','Gary Lineker','Michel Platini','Diego Maradona','Paolo Rossi','c','200'),
('Jaki film, oparty na faktach, opowiada historię dwóch braci uciekających z Polski do Danii w schowku pod TIR-em ?',' „Trzy stopy nad ziemią”','„300 mil do nieba”','„U kresu drogi”','„Ucieczka”','b','200'),
('Jak nazywa się najstarsze pismo słowiańskie ?','sanskryt','minuskuł','głagolica','cyrylica','c','200'),
('Która z greckich bogiń była opiekunką dzieci i sierot oraz ogniska domowego ?','Hera','Artemida','Demeter','Hestia','d','200'),
('Jak nazywa się gruczoł wydzielający insulinę ?','trzustka','nadnercza','tarczyca','przysadka mózgowa','a','200'),
('Gra, w której dwie konne drużyny podbijają drewnianą piłeczkę młotkami o długich rękojeściach to:','pelota','polo','krykiet','curling','b','200'),
('Jaką roślinę nazywamy niekiedy słodkim ziemniakiem ?','batat','bambus','jams','burak','a','200'),
('Jak nazywali się hiszpańscy zdobywcy większości obszarów Ameryki Środkowej i Południowej ?','corriegidorzy','konkwistadorzy','gerylasi','alkadowie','b','200'),
('Łódź wykonana z jednego pnia drzewa to:','dłubanka','sampan','gondola','karawela','a','200'),
('Które z wymienionych gór nie leżą na półwyspie ?','Góry Betyckie','Góry Skandynawskie','Apeniny','Kaukaz','d','200'),
('Założycielem jakiego zespołu pieśni i tańca był Stanisław Hadyna ?',' „Mazowsze”','„Śląsk”','„Gawęda”','„Zespół Pieśni i Tańca AWF”','b','200'),
('Który film Alfreda Hitchcocka opowiada historię psychopatycznego właściciela motelu ?',' „Ptaki”','„Złodziej w hotelu”','„Okno na podwórze”','„Psychoza”','d','200'),
('Przedstawiciele której z podanych populacji ludzkich zaliczani są do najniższych ?','Masajowie','Berberowie','Aborygeni','Pigmeje','d','200'),
('Najmniejsza jednostka ilości informacji to:','bajt','octet','piksel','bit','d','200'),
('Który z mistrzów sportowych został rozstrzelany w Palmirach przez hitlerowców ?','Zatopek','Kusociński','Ślusarski','Malinowski','b','200'),
('Imię tytułowego „wujaszka” w komedii Antoniego Czechowa to:','Sasza','Sierioża','Wania','Wasia','c','200'),
('Jakie zwierzę jest symbolem Kampinoskiego Parku Narodowego ?','żubr','łoś','wilk','niedźwiedź','b','200'),
('W jakim mieście znajduje się Maracana, jeden z większych kompleksów sportowych na świecie ?','w Rio de Janeiro','w Casablance','w Bilbao','w Madrycie','a','200'),
('Jak miał na imię Rzecki, subiekt z powieści Bolesława Prusa pt. „Lalka” ?','Ignacy','Teodor','Stanisław','Tadeusz','a','200'),
('Ile chromosomów zawiera plemnik człowieka ?','17','20','23','26','c','200'),
('Kapitanem jakiej reprezentacji na Mistrzostwach Świata w piłce nożnej w USA był Gheorghe Hagi ?','Rumunii','Włoch','Bułgarii','Hiszpanii','a','200'),
('Jakiego wynalazku nie użyto w I wojnie światowej ?','czołgu','łodzi podwodnej','gazów trujących','broni jądrowej','d','200'),
('Skąd wywodzi się joga ?','z Indii','z Chin','z Japonii','z Korei','a','200'),
('Kto wygrał konkurs skoków na dużej skoczni podczas Igrzysk Olimpijskich w Sapporo w 1972 roku ?','Fijas','Fortuna','Skupień','Małysz','b','200'),
('Statek handlowy przewożący najczęściej ładunki płynne to:','masowiec','prom','zbiornikowiec','drobnicowiec','c','200'),
('Skąd pochodzi Pablo Picasso ?','z Hiszpanii','z Holandii','z Francji','z Austrii','a','200'),
('Jak nazywa się jedyny w Polsce pająk wodny ?','ptasznik','topik','krzyżak','tarantula','b','200'),
('Jak nazywamy wiadukt używany do oddzielenia arterii komunikacyjnej od lokalnego ruchu ?','zwrotnica','estakada','trakcja','bocznica','b','200'),
('Co ma pod stopami Wenus z obrazu Sandro Botticellego pt. „Narodziny Wenus” ?','łąkę','muszlę','płatki róż','perły','b','200'),
('Ile pierwszych kręgów kręgosłupa ssaków to kręgi szyjne ?','8','7','6','5','b','200'),
('Która z wysp nie znajduje się na Morzu Śródziemnym ?','Gotlandia','Majorka','Malta','Rodos','a','200'),
('Ile wierzchołków ma sześcian ?','12','10','8','6','c','200'),
('Które z imion nie należy do żadnego z braci Marx ?','Groucho','Buster','Chico','Harpo','b','200'),
('W jakim państwie znajduje się Innsbruck, słynny ośrodek sportów zimowych ?','w Austrii','w Szwajcarii','w Niemczech','w Liechtensteinie','a','200'),
('Najsłynniejszą budowlę Indii, Tadż Mahal, cesarz Szahdżahan kazał zbudować w hołdzie:','poległemu synowi','zmarłej córce','zmarłej żonie','przyjacielowi','c','200'),
('Który z narodów jako pierwszy wytwarzał różne przedmioty z porcelany ?','Chińczycy','Brytyjczycy','Niemcy','Francuzi','a','200'),
('Który teledysk Michaela Jacksona, trwający 14 minut, zdobył nagrodę Grammy ?',' „Into the Closet”','„Beat It”','„Thriller”','„Billie Jean”','c','200'),
('Który z zawodników nie przyda się w drużynie baseballowej ?','bramkarz','miotacz','łapacz','odbijający','a','200'),
('Armator to osoba fizyczna lub prawna eksploatująca:','skład kolejowy','lotnisko','złoża naturalne','statek morski','d','200'),
('Borsuk jest zwierzęciem:','mięsożernym','padlinożernym','wszystkożernym','roślinożernym','c','200'),
('Która z wymienionych osób nie była gwiazdą komedii muzycznej ?','Harold Lloyd','Fred Astaire','Ginger Rogers','Gene Kelly','a','200'),
('Które z wymienionych gór znajdują się najbardziej na zachód ?','Karkonosze','Izerskie','Sowie','Beskid Niski','b','200'),
('Siergiej Bubka to wielokrotny rekordzista świata w:','skokach do wody','skoku w dal','skoku w wzwyż','skoku o tyczce','d','200'),
('Częścią siodła nie jest:','siedzisko','strzemię','tybinka','wędzidło','d','200'),
('Który z wymienionych papierów wytwarzany jest ręcznie ?','afiszowy','banknotowy','czerpany','kreślarsko-rysunkowy','c','200'),
('Jaki zespół starali się naśladować bohaterowie filmu Radosława Piwowarskiego pt. „Yesterday” ?','The Beatles','The Animals','The Who','the Doors','a','200'),
('Jak nazywa się znany tor wioślarski w Poznaniu ?','Padwa','Malta','Sycylia','Elba','b','200'),
('Minerałem nie jest:','piryt','promet','kaolinit','kwarc','b','200'),
('Która z wymienionych brył nie jest wielościanem ?','stożek','prostopadłościan','ostrosłup','równoległościan','a','200'),
('W skład trylogii Henryka Sienkiewicza nie wchodzi:',' „Pan Wołodyjowski”','„Quo vadis”','„Ogniem i mieczem”','„Potop”','b','200'),
('Która z wymienionych witamin w kosmetyce zwana jest „witaminą młodości” ?','witamina P','witamina K','witamina E','witamina H','c','200'),
('„W malinowym chruśniaku, przed ciekawych wzrokiem” napisał:','Bolesław Leśmian','Jan Lechoń','Konstanty Ildefons Gałczyński','Kazimierz Przerwa-Tetmajer','a','200'),
('Naukowcy opierający swe badania na kopalnych szczątkach i odciskach organizmów to:','speleolodzy','glacjolodzy','paleontolodzy','mineralodzy','c','200'),
('Który z wymienionych zespołów stworzył legendarny album pt. „The Wall” ?','The Rolling Stones','Pink Floyd','Genesis','Metallica','b','200'),
('Jaka formacja nie walczyła konno ?','dragoni','szwoleżerowie','ułani','pikinierzy','d','200'),
('Symbol władzy królewskiej w starożytnym Egipcie, mający kształt stylizowanego węża-kobry to:','bicz','pastorał','ureusz','infuł','c','200'),
('Ministrem spraw wewnętrznych w rządzie Jana Olszewskiego, autorem słynnej listy agentów, był:','A. Macierewicz','L. Kaczyński','R. Sikorski','R. Szeremietiew','a','200'),
('Jaki kraj uważa się za kolebkę hokeja na lodzie ?','Rosję','Niemcy','Szwecję','Kanadę','d','200'),
('Która z wymienionych liczb nie jest podzielna przez 7 ?','49','61','84','98','b','200'),
('W obszarze zabudowanym maksymalna prędkość kierującego pojazdem samochodowym wynosi:','45 km/h','50 km/h','60 km/h','70 km/h','c','200'),
('Jak nazywał się odwieczny wróg Sherlocka Holmesa ?','doktor Mabuse','Fantomas','profesor Moriarty','Mr. Hyde','c','200'),
('Która z postaci komiksowych to samotny kowboj ?','Batman','Spiderman','Gordon Flash','Lucky Luke','d','200'),
('O kimś, kto miał dużo szczęścia, mówimy, że „trafiło mu się, jak ślepej kurze...” :','perła','laska','ziarno','płot','c','200'),
('Kim byli dla siebie kompozytorzy austriaccy o tym samym imieniu i nazwisku – Johann Strauss ?','ojcem i synem','dziadkiem i wnukiem','wujkiem i bratankiem','obcymi osobami','a','200'),
('Spektakl teatralny organizowany z okazji jubileuszu aktora lub na jego rzecz to:','prapremiera','benefis','memoriał','beneficjum','b','200'),
('Jakim elementem architektonicznym jest gargulec ?','ozdobą nad drzwiami','zwieńczeniem komina','oknem w dachu','zakończeniem rynny','d','200'),
('Który z wymienionych pierwiastków chemicznych nie jest gazem ?','rod','fluor','wodór','hel','a','200'),
('Rasą psów zaprzęgowych jest:','rottweiler','kuwasz','malamut alaskan','komondor','c','200'),
('Koło jakiego miasta znajduje się znany z fabryk mebli – Swarzędz ?','Krakowa','Katowic','Gdańska','Poznania','d','200'),
('Kto 1 lipca 1997 roku przekazał Chinom władzę nad Hongkongiem ?','Francja','Wielka Brytania','Holandia','Hiszpania','b','200');


INSERT INTO Questions (question, answerA, answerB, answerC, answerD, correctAnswer, points )VALUES
('Jakie imię otrzymała fregata rakietowa USS „Clark”, podarowana Polsce przez Stany Zjednoczone ?','Kazimierz Pułaski','Tadeusz Kościuszko','Ignacy Paderewski','Józef Karge','a','400'),
('Kiedy obchodzony jest Dzień Matki ?','21 stycznia','26 maja','8 marca','23 czerwca','b','400'),
('Kto w 1956 roku w Poznaniu straszył „odrąbywaniem rąk” ?','Józef Cyrankiewicz','Bolesław Bierut','Władysław Gomułka','Mieczysław Moczar','a','400'),
('Na co stoczyli pojedynek Miętus i Syfon, bohaterowie powieści Witolda Gombrowicza pt. „Ferdydurke” ?','na pistolety','na słowa','na szable','na miny','d','400'),
('„Iron man” to przebój grupy:','Deep People','Black Sabbath','AC/DC','Led Zeppelin','b','400'),
('Kim dla Juliusza Kossaka była Zofia Kossak-Szczucka ?','wnuczką','matką','żoną','córką','a','400'),
('Zinedine Zidane to piłkarz grający w czasie finałów Mistrzostw Świata we Francji w 1998 roku w reprezentacji:','Włoch','Francji','Hiszpanii','Brazylii','b','400'),
('Jan Kułakowski został w 1998 roku głównym negocjatorem Polski:','z Unią Europejską','z NATO','z Federacją Rosyjską','z NAFTA','a','400'),
('Ile województw w Polsce było przed II wojną światową bez miasta wydzielonego Warszawa ?','10','16','35','49','b','400'),
('Kim w filmie pt. „Chłopi” dla Macieja Boryny jest Jagna Paczesiówna ?','siostrą','żoną','bratową','świekrą','b','400'),
('Nazwa zakładów zbrojeniowych w Skarżysku-Kamiennej, z których w 1999 roku skradziono rakiety przeciwlotnicze to:','„Łucznik”','„Bumar-Łabędy”','„Mesko”','„VIS”','c','400'),
('Kto skomponował muzykę do wiersza Cypriana Kamila Norwida pt. „Bema pamięci rapsod żałobny” ?','Marek Grechuta','Tadeusz Woźniak','Stanisław Soyka','Czesław Niemen','d','400'),
('Grzegorz Markowski w piosence pt. „Wyspa, drzewo, zamek” śpiewa, że został mu spadek po:','babci','rodzicach','dziewczynie','cioci','c','400'),
('Do jakiego kraju należy Grenlandia ?','do Wielkiej Brytanii','do USA','do Danii','do Szwecji','c','400'),
('Jak nazywał się teatr studencki, działający w Gdańsku w latach 1954-1960 ?','„Bim-Bom”','„Zielony Balonik”','„Qui Pro Quo”','„STS”','a','400'),
('Jak inaczej nazywamy absynt ?','piołunówka','anyżówka','jałowcówka','miętówka','a','400'),
('Co było na początku świata w mitologii greckiej ?','Słowo','Chaos','Kosmos','Rozum','b','400'),
('Tajemnica zabójstwa Laury Palmer jest jednym z głównych tematów serialu:','„Twin Peaks”','„Przystanek Alaska”','„Z Archiwum X”','„Crime Story”','a','400'),
('Kto nazywany jest „prymasem tysiąclecia” ?','August Hlond','Józef Glemp','Adam Sapiecha','Stefan Wyszyński','d','400'),
('W jakim mieście zorganizowano w 1660 roku pokój, który zakończył wojny Polski ze Szwecją o Inflanty ?','w Oliwie','w Toruniu','w Rydze','w Kaliszu','a','400'),
('Zenitówkę potocznie określa się jako:','moździerz','działo przeciwlotnicze','działo bezodrzutowe','haubicoarmatę','b','400'),
('Którego arbitra na Mistrzostwach Europy w 2000 roku czescy kibice i dziennikarze nazwali „łysym potworem z Marsa” ?','Ursa Meiera','Dicka Jola','Pierlugi Collinę','Andersa Friska','c','400'),
('W jakim kraju leży Pustynia Gibsona ?','w Meksyku','w Australii','w USA','w Algierii','b','400'),
('Boom na gry komputerowe, w których gracz patrzy oczami kierowanego przez siebie wojownika, zapoczątkował:','„Panzer General”','„The Last Starfighter”','„Silent Service”','„Doom”','d','400'),
('Muniek Staszczyk śpiewa w utworze pt. „Gwiazdka”, że za pierwszą wypłatę kupi sobie:','czekoladę','armatę','gitarę','pralkę','b','400'),
('W jakim mieście znajduje się muzeum  Atomium ?','w Paryżu','w Nowym Jorku','w Brukseli','w Berlinie','c','400'),
('Ozdobny uchwyt metalowy na drzwiach, czasem w kształcie głowy lwa to:','antaba','abakus','impost','tralka','a','400'),
('Czyim ojcem nie był szekspirowski król Lear ?','Goneryli','Regany','Kordelii','Ofelii','d','400'),
('Na jakim placu w 1987 roku wylądował niemiecki pilot-amator Matthias Rust ?','na Placu Defilad w Warszawie','na Placu Tiananmen w Pekinie','na Placu Czerwonym w Moskwie','na Placu Aleksandra w Berlinie','c','400'),
('Modne w XVIII wieku przybranie z ozdobnej tkaniny, noszone przez mężczyzn pod szyją to:','żabot','lamówka','turniura','matinka','a','400'),
('Dział matematyki badający zależności między bokami i kątami trójkątów to:','stereometria','trygonometria','triangulacja','trilateracja','b','400'),
('Jakie grupie zawodowej patronuje św. Florian ?','fryzjerom','strażakom','marynarzom','murarzom','b','400'),
('Orkę, największego przedstawiciela delfinowatych nazywamy inaczej:','miecznikiem','rybą piłą','długoszparem','barrakudą','a','400'),
('W jakim kraju toczyła się „wojna dwóch róż” ?','we Francji','w Hiszpanii','w Austrii','w Anglii','d','400'),
('Którą roślinę nazywamy „gruszką miłosną” ?','karczoch','bakłażan','awokado','cykorię','b','400'),
('Kto w kinowej wersji filmu pt. „Asterix i Obelix kontra Cezar” odtwarzał rolę siłacza Obelixa ?','Gerard Depardieu','Roberto Benigni','Christian Clavier','Michel Piccoli','','400'),
('Pismo literackie wydawane od 1986 roku i redagowane przez Roberta Tekielego to:','„Res Publika”','„Znak”','„bruLion”','„Twórczość”','c','400'),
('Bojowniczki o przyznanie kobietom praw wyborczych to:','sufrażystki','feministki','separatystki','amazonki','a','400'),
('Które z podanych słów nie oznacza aureoli ?','mandorla','nimb','gloria','aurora','d','400'),
('Jaki zespół wystąpił na warszawskim Służewcu w sierpniu 1997 roku ?','Pearl Jam','Aerosmith','Oasis','U2','d','400'),
('Jak długo trwa filmowy związek Kim Basinger i Mikey’ Rourke w filmie Adriana Lyne’a ?','8 i pół tygodnia','9 i pół tygodnia','10 i pół tygodnia','11 i pół tygodnia','b','400'),
('Gdzie w czerwcu 2000 roku odbyła się konferencja „Ku wspólnocie demokracji” ?','w Davos','w Paryżu','w Warszawie','w Madrycie','c','400'),
('Jak inaczej nazywa się ziele angielskie ?','piment','cayenne','curry','tabasco','a','400'),
('Najjaśniejszą gwiazdą naszego firmamentu jest:','Proxima Centauri','Syriusz','Toliman','Canopus','b','400'),
('Jaka drużyna w sezonie piłkarskim 1999/2000 zdobyła tytuł mistrza Polski ?','Hoop Polonia Warszawa','Wisła Kraków','Legia Daewoo Warszawa','Widzew Łódź','a','400'),
('Według obowiązującej Konstytucji RP prawo łaski stosuje:','premier','Trybunał Stanu','prezydent','Sąd Najwyższy','c','400'),
('Pisarz i publicysta, miłośnik i popularyzator jazzu w Polsce, który w 1967 roku osiedlił się w USA to:','Leopold Tyrmand','Witold Gombrowicz','Stanisław Dygat','Stanisław Barańczak','a','400'),
('Były szef Sztabu Generalnego, kandydujący na prezydenta RP w 2000 roku to:','Zbigniew Zalewski','Tadeusz Wilecki','Henryk Szumski','Piotr Kołodziejczyk','b','400'),
('Słynny astronom Jan Heweliusz był:','torunianinem','gdańszczaninem','szczecinianinem','krakowianinem','b','400'),
('W jakiej piosence zespołu Queen brzmi operowy zaśpiew: „Mamma Mia, Mamma Mia – Mamma Mia Let Me Go” ?','„Bohemian Rhapsody”','„Show Must Go On”','„Innuendo”','„Somebody To Love”','a','400'),
('Który z pisarzy był mężem Kaliny Jędrusik ?','Jerzy Andrzejewski','Marek Hłasko','Stanisław Dygat','Tadeusz Konwicki','c','400'),
('Madeleine Albright, sekretarz stanu USA, odebrała doktorat „honoris causa” Uniwersytetu:','Jagiellońskiego','Gdańskiego','Warszawskiego','Poznańskiego','b','400'),
('Z jakiego kraju pochodził zespół Omega, znany m.in. z przeboju pt. „Dziewczyna o perłowych włosach” ?','z Czech','z Niemiec','z Bułgarii','z Węgier','d','400'),
('Kto gra rolę tańczącej w klubie go-go, byłej pracownicy FBI w filmie pt. „Striptease” ?','Kim Basinger','Demi Moore','Holy Hunter','Sharon Stone','b','400'),
('Sherry to nazwa wzmacnianego wina pochodzącego:','z Francji','z Hiszpanii','z Włoch','z Niemiec','b','400'),
('Który z wymienionych metali nie należy do grupy metali ciężkich ?','złoto','miedź','chrom','magnez','d','400'),
('Z jakiego kraju pochodzi rasa psa chow-chow ?','z Niemiec','z Wielkiej Brytanii','z Francji','z Chin','d','400'),
('Amerykański finansista, który finansuje m.in. Fundację im. Stefana Batorego to:','George Soros','Bill Gates','Lamberto Dini','Nelson Rockefeller','a','400'),
('Niektóre państwa zbojkotowały olimpiadę w Moskwie w 1980 roku, ponieważ sowieci wkroczyli:','do Wietnamu','do Afganistanu','do Laosu','do Czechosłowacji','b','400'),
('Znak zodiaku, którego łacińska nazwa brzmi „gemini” to:','Bliźnięta','Panna','Wodnik','Waga','a','400'),
('Który z francuskich monarchów został zamordowany przez buntowników w 1792 roku ?','Ludwik XI','Karol IX','Ludwik XVI','Henryk IV','c','400'),
('Których owoców nie jada się na surowo ?','kiwi','pigwy','grejpfruta','granatu','b','400'),
('Współczesnym Mozartowi kompozytorem był:','Giuseppe Verdi','Giacomo Puccini','Joseph Haydn','Piotr Czajkowski','c','400'),
('W jakiej dyscyplinie sportu Jacek Wszoła ustanowił rekord świata w 1980 roku ?','w skoku o tyczce','w biegu przez płotki','w skoku wzwyż','w skoku w dal','c','400'),
('Który król panował w Polsce w czasie potopu szwedzkiego ?','Stefan Batory','Jan Kazimierz','Zygmunt Stary','Jan Sobieski','b','400'),
('„Zefirek”, zaprojektowany przez Biuro Konstrukcyjne Zakładów Radiowych „Eltra” był:','wentylatorem','suszarką','radiem','adapterem','a','400'),
('Król-kapłan Szalemu, który pobłogosławił Abrahama powracającego z wyprawy wojennej to:','Azariasz','Jeroboam I','Melchizedek','Ezechiasz','c','400'),
('Z którym z podanych państw nie graniczy Chile ?','z Argentyną','z Peru','z Boliwią','z Brazylią','d','400'),
('Kto nie pracuje nad przygotowaniem książki do druku pod względem językowym ?','adiustator','korektor','redaktor','metrampaż','d','400');




